---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: blog
  label: Blog Content
  create: all
  match: "**/*"
  new_doc_ext: mdx
- type: directory
  path: content/blog
  label: Blog Settings
  create: none
  match: "**/*"
- type: document
  path: content/react-intl/en.json
  label: Content
- type: document
  path: content/events/events.json
  label: Events
- type: document
  path: content/banner/banner.json
  label: Banner
- type: document
  path: package.json
  label: Scripts
  read_only: true
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: yarn install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn forestry:preview
